//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniAdminPanel.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDb)\\v11.0;AttachDbFilename=C:\\Users\\Ivaylo\\Source\\Repos\\OOP2016" +
            "EShopHA\\EShopHA\\EShopHA\\App_Data\\aspnet-EShopHA-20160524043511.mdf;Initial Catal" +
            "og=aspnet-EShopHA-20160524043511;Integrated Security=True")]
        public string aspnet_EShopHA_20160524043511ConnectionString {
            get {
                return ((string)(this["aspnet_EShopHA_20160524043511ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=C:\\Users\\Ivaylo\\Source\\Repos\\OOP2016" +
            "EShopHA\\EShopHA\\EShopHA\\App_Data\\ProductDBContext.mdf;Integrated Security=True")]
        public string ProductDBContextConnectionString {
            get {
                return ((string)(this["ProductDBContextConnectionString"]));
            }
        }
    }
}
